config/routes.rb
Rails.application.routes.draw do
  root 'players#new'
  get '/playing', to: 'players#edit_multiple'
  post '/playing', to: 'players#edit_multiple'

  resources :players, only: [:create, :new, :edit, :update, :destroy_all, :edit_multiple, :update_multiple]
  resources :players do
    collection do
      delete :destroy_all
      post 'update_multiple'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord

  validates :name, uniqueness: true, length: { maximum: 20 }, presence: true
  attribute :points, default: 0

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, world!"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
    @players = Player.all
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to root_path
    else
      flash[:error] = "この名前は既に使われています。"
      redirect_to root_path
    end
  end

  def destroy_all
    Player.destroy_all
    redirect_to root_path 
  end

  def edit_multiple
    @players = Player.all
  end

  def update_multiple
    @players = Player.all
    @players.each_with_index do |player, i|
      added_points = player.points + params[:players].values[i]['points'].to_i
      @player = Player.find(player.id)
      @player.update(points: added_points)
    end
    redirect_to playing_path
  end

  private
    def player_params
      params.require(:player).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <header>
      <h1>UNOポイント管理アプリ</h1>
    </header>
    <%= yield %>
    <%# <%= debug(params) if Rails.env.development? %> 
  </body>
</html>

app/views/players/_index.html.erb
<div class="player-list">
  <h3>プレイヤー登録</h3>
  <% if @players.nil? || @players.empty? %>
    <p>プレイヤーを登録しよう！</p>
  <% else %>
    <%= @players.each do |player| %>
      <%= player.name %><p></p>
    <% end %>
  <% end %>
</div>

app/views/players/edit_multiple.html.erb
<div class="playing-wrapper">
  <tr>
    <th>プレイヤー名｜</th>
    <th>現在のポイント｜</th>
    <th>ポイント増減</th>
  </tr>
  <%= form_tag update_multiple_players_path do %>
    <% for player in @players %>
      <%= fields_for "players[]", player do |f| %>
        <%= f.hidden_field :id %>
        <%= player.name.ljust(14, '_')%>
        <%= player.points.to_s.ljust(16, '_')%>
        <%= f.text_field :points , size: 5, value: nil%>
        <input type="radio" name="win">WIN
        <p></p>
      <% end %>
    <% end %>
    <%= submit_tag "確定" %>
  <% end %>
  <%= button_to "ゲーム終了！", destroy_all_players_path, method: :delete%>
</div>

app/views/players/new.html.erb
<p class="introduction">Play UNO in formal Way!</p>

<div class="players-index-create">
  <div class="players-index">
    <%= render 'index' %>
  </div>

  <div class="create-players">
    <%= form_with(model: @player, method: :post) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit "追加する", class: "btn btn-primary" %>
    <% end %>
    <%= flash[:error]%>
  </div>
</div>

<div class="buttons">
  <%= button_to "Delete All", destroy_all_players_path, method: :delete%>
  <%= button_to "Start Game", playing_path %>
</div>